// sketch.js - Main p5.js entry point
// Ported from OuterWilds_TextAdventure.pde

/*** CONSTANTS ***/
const TEXT_SIZE = 14;

/*** DEBUG FLAGS ***/
const EDIT_MODE = false;
const SKIP_TITLE = false;
const START_WITH_LAUNCH_CODES = false;
const START_WITH_CLUES = false;
const START_WITH_SIGNALS = false;
const START_WITH_COORDINATES = false;

/*** GLOBALS ***/
let locator;
let gameManager;
let timeLoop;
let messenger;
let feed;
let playerData;

// sectorJSONData and fontData are initialized and populated via <script> tags
// in index.html (generated by tools/convert-assets.js), so the game works from
// file:// without a local server.

let lastMillis = 0;
let deltaMillis = 0;

function setup() {
  createCanvas(960, 720);
  noSmooth();
  colorMode(HSB, 360, 100, 100, 100);
  rectMode(CENTER);
  ellipseMode(CENTER);
  // CSS font stack as fallback; actual rendering uses the bitmap font system (bitmapFont.js)
  textFont('Consolas, "Courier New", monospace');

  // Initialize bitmap fonts from pre-parsed data (generated by tools/convert-assets.js)
  BitmapText.registerFont(14, new BitmapFont(fontData[14]));
  BitmapText.registerFont(18, new BitmapFont(fontData[18]));
  BitmapText.init();
  setupBitmapTextOverrides();

  smallFont();

  // Prevent browser context menu so right-click works for game actions (e.g. probe)
  document.querySelector('canvas').addEventListener('contextmenu', e => e.preventDefault());

  AudioManager.init();

  initGame();
}

function initGame() {
  const startLoadTime = millis();

  timeLoop = new TimeLoop();
  messenger = new GlobalMessenger();
  feed = new StatusFeed();
  gameManager = new GameManager();
  playerData = new PlayerData();

  gameManager.newGame();

  console.log('Load time: ' + (millis() - startLoadTime));
}

function draw() {
  gameManager.runGameLoop();

  deltaMillis = millis() - lastMillis;
  lastMillis = millis();
}

function frequencyToString(frequency) {
  switch (frequency) {
    case Frequency.TRAVELER: return 'Traveler Frequency';
    case Frequency.BEACON: return 'Distress Beacon';
    case Frequency.QUANTUM: return 'Quantum Fluctuations';
    default: return '';
  }
}

function smallFont() {
  textSize(14);
  BitmapText.setFont(14);
}

function mediumFont() {
  textSize(18);
  BitmapText.setFont(18);
}
